apiVersion: v1
kind: Service
metadata:
  name: service
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": serving-cert-secret
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
